name: CI master

on:
  push:
    branches:
      - 'master'

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d .
